THERESASILIEZAR-TJSZ/magical_file_update.rb
=> I love magic

SeanNarvasa-snarvasa/magical_file_update.rb
=> Pull Request #1

SeanFalese-falese/magical_file_update.rb
=> Adding magic_file_update.rb

MorganHolland-spoofhopper/magical_file_update.rb
Uploading magic file for the first time!
=> initial commit

NicoleBorgaard-Borgaard/where_did_all_these_cats_come_from.rb
@chylaudes I couldn't find a cat emoticon so here's a cactus :cactus:
=> found some cats

RaymondLiaw-rayliaw/reverse_it.rb
just wanted to try it out with using an each enumerator instead of the while loop. sry! :)
=> replace while loop with each_index

PaigeKirstein-prkirstein/reverse_it.rb
=> my reverse it exercise

EdwardSung-kaiyusung/lesson_02_hw.rb
=> reverse method

AnneGarlandBerry-annegarlandberry/magiical_file_update.rb, AnneGarlandBerry-annegarlandberry/test.rb
=> Add reverse.it 

THERESASILIEZAR-TJSZ/hw_2/drome.rb
Here's my homework on the palindrone/reverse
=> homework 2

SeanFalese-falese/hw_2/reverse_it.rb, SeanFalese-falese/hw_3/hash_party.rb
=> Hw_3 Pull request

README.md
I'm seeing a lot of homework without these directories.
=> Add explanation for hw_x directories

PaigeKirstein-prkirstein/hash_practice.rb
Here is my hash homework from lesson three. Per assignment, included the following methods:
.length, .merge, .merge!, .keys, .values, .has_key?, .has_value?
=> {lesson three: hash homework}

LeslieGomez-MojoBoot/car_lot.rb, LeslieGomez-MojoBoot/hash_prac.rb
Would love to know if the add_cars method is on track for the car_lot exercise that was done in class (I had to miss). I was unable to make it work without calling cars in the argument and then down below when I wanted to "run" the method?!? :
def add_cars(cars,*others)
+  cars.push(*others)
+end
add_cars(cars, toyota)
Is that because it is a local variable and not an instance variable? (Please don't assume I know what that means 100%) Is there a way to access the cars array from within the add_cars method without doing that?
=> submit car_lot for review

AnneGarlandBerry-annegarlandberry/hash_test.rb, AnneGarlandBerry-annegarlandberry/hw_3/fortune.rb, AnneGarlandBerry-annegarlandberry/hw_3/hash.rb
homework from Monday--testing new hash methods
=> adding Monday's homework--experiment w/ new hash methods

SeanFalese-falese/hw_4/car_lot.rb, SeanFalese-falese/hw_4/get_cars_i_love_post.rb, SeanFalese-falese/hw_4/love_post.rb, SeanFalese-falese/hw_5/get_it.rb
I tried to do something different with the get_cars_i_love_post.rb file in the hw_4 directory.
i call an edmunds API to return JSON based on a user supplied make and year
i parse to json and error check the REST response and prompt for any errors
next i try to iterate through the array and pass the model niceName and model year ID to a hash method.
the hash method errors saying no arguements provided.  i compared against the get_it.rb homework that works and can't spot any differences.  any help would be appreciated.
=> hw_4 and hw_5

LeoTishin-Lansaro/hw_5/JSON practice, LeoTishin-Lansaro/hw_5/JSON practice Reddit, LeoTishin-Lansaro/hw_5/Mashable_CSV.csv
Hi Instructors team, I know I suppose to save it on something like on a "non-master" branch, but looks like those branches (lesson_4/lesson_5) are created only at class exercises level. Do I need to create another branches on homework level?
=> JSON practice Reddit/Mashable

EdwardSung-kaiyusung/homework_lesson_4/car_lot.rb, EdwardSung-kaiyusung/homework_lesson_4/love_post.rb, EdwardSung-kaiyusung/homework_lesson_5/mashable.csv, EdwardSung-kaiyusung/homework_lesson_5/mashable_get_it.rb, EdwardSung-kaiyusung/homework_lesson_5/reddit.csv, EdwardSung-kaiyusung/homework_lesson_5/reddit_get_it.rb
Homework for lesson 4 and lesson 5.
=> lesson_4 and lesson_5 homework

MikeCassaro-mcc33/hw_4/car_lot.rb, MikeCassaro-mcc33/hw_4/love_post.rb, MikeCassaro-mcc33/hw_5/get_it.rb
Hi,
Here is the Love_Post & Car_Lot hw assignments. Please let me know of any questions/concerns.
Thanks,
Mike
=> Love Post & Car lot HW

AnneGarlandBerry-annegarlandberry/hw_5/Combinedhmwk.rb, AnneGarlandBerry-annegarlandberry/hw_5/car_lot.rb, AnneGarlandBerry-annegarlandberry/hw_5/get_it.rb, AnneGarlandBerry-annegarlandberry/hw_5/love_post.rb, AnneGarlandBerry-annegarlandberry/hw_5/mashable.rb
includes love_post.rb, car_lot.rb, mashable and reddit (each separate) and mashable and reddit combined in one method that I re-did on my own after doing this with Kisha yesterday in office hours.
=> adding this week's homework

AliviaBlount-amblount/hw_5/get_it.rb, AliviaBlount-amblount/hw_5/get_it_practice.rb, AliviaBlount-amblount/hw_5/mashable.rb
=> homwwork 5 added

PaigeKirstein-prkirstein/hw_4/car_lot.rb
=> homework 4

MorganHolland-spoofhopper/hw_05 (get_it)/get_it.rb, MorganHolland-spoofhopper/hw_05 (get_it)/story_csv.csv
Added separate methods for mashable. Not sure what the cleanest way to do this was since each story has a different hash/array 'address' in Reddit vs. Mashable. Could have done an 'if' statement and just used one method for each steps but seemed cumbersome. Is there some clever way to simplify the 'address' of each story down from story['data']['children']['data'] to something else so I could use a single line of code to assign a reddit OR a mashable story to an array?
Thanks!
=> added Mashable methods to get_it.rb

LeslieGomez-MojoBoot/HW-7/thermostat.rb
=> add thermostat homework

PaigeKirstein-prkirstein/hw_6/rise_of_robot.rb, PaigeKirstein-prkirstein/hw_6/security_system.rb, PaigeKirstein-prkirstein/hw_6/thermostat.rb
Here's my homework 6! I added a note in there, but FYI (hope it's okay!) I went ahead and actually made a new assignment (inspired by Travis!) with class "security" because I found working from a blank state was the best way to figure out if I actually understood anything.
=> homework 6

SeanFalese-falese/hw_4/get_cars_i_love_post.rb, SeanFalese-falese/hw_6/rise_of_robots.rb, SeanFalese-falese/hw_6/thermostat.rb
Rise of the robots and thermostat with private methods checking in.
=> PR for homework 6

YelenaKozlova-kreatyvdesign/hw_6/rise_of_robot.rb, YelenaKozlova-kreatyvdesign/hw_6/thermostat.rb, YelenaKozlova-kreatyvdesign/hw_8/lib/apartment.rb, YelenaKozlova-kreatyvdesign/hw_8/lib/building.rb, YelenaKozlova-kreatyvdesign/hw_8/lib/renter.rb, YelenaKozlova-kreatyvdesign/hw_8/real_estate.rb
added real_estate.rb and supporting files
also some clean up and notes on homework 6 files
=> Homework 8

SeanFalese-falese/hw_6/thermostat.rb, SeanFalese-falese/hw_8/lib/apartment.rb, SeanFalese-falese/hw_8/lib/building.rb, SeanFalese-falese/hw_8/lib/tenants.rb, SeanFalese-falese/hw_8/real_estate.rb
PR for real estate homework.  classes are fun!
=> commit of all thermostat changes and homework 8

MikeCassaro-mcc33/hw_8/lib/apartment.rb, MikeCassaro-mcc33/hw_8/lib/building.rb, MikeCassaro-mcc33/hw_8/lib/renter.rb, MikeCassaro-mcc33/hw_8/real_estate.rb
The Real Estate HW with the 3 associated files for each class. Please let me know of any questions/concerns.
Thanks,
Mike
=> Real Estate HW

PaigeKirstein-prkirstein/hw_8/examine/lib/apartment.rb, PaigeKirstein-prkirstein/hw_8/examine/lib/building.rb, PaigeKirstein-prkirstein/hw_8/examine/lib/renter.rb, PaigeKirstein-prkirstein/hw_8/examine/real_estate.rb
Here's my Real Estate assignment. There's still a few more improvements I'd like to make, but wanted to get it over not (too) late so handing it in as in. Pointed out where I'm still having issues in the comments. Thanks SO much for all of the help!
=> Real Estate Assignment

README.md
I bumped the due-date by one day for the holiday.
=> Add homework 10

AnneGarlandBerry-annegarlandberry/hw_5/get_it.rb, AnneGarlandBerry-annegarlandberry/hw_7/real_estate.rb
can't remember if I created a pull request for this when I uploaded Monday. If not, so sorry.
=> adding real_estate

RaymondLiaw-rayliaw/hwk_13/music_app/Gemfile, RaymondLiaw-rayliaw/hwk_13/music_app/Gemfile.lock, RaymondLiaw-rayliaw/hwk_13/music_app/app/assets/stylesheets/application.css, RaymondLiaw-rayliaw/hwk_13/music_app/app/controllers/reviews_controller.rb, RaymondLiaw-rayliaw/hwk_13/music_app/app/views/artists/show.html.erb, RaymondLiaw-rayliaw/hwk_13/music_app/app/views/reviews/_form.html.erb, RaymondLiaw-rayliaw/hwk_13/music_app/app/views/songs/show.html.erb, RaymondLiaw-rayliaw/hwk_13/music_app/config/routes.rb
Only part I'm sort of struggling with is using views slightly different on polymorphic models depending on which type. I'm assuming though that, by doing that, you're not treating it correctly as they should be separate models at that point then if they're being treated different based on state? But, it does seem you may want to render the associated value differently at times though...
=> Got polymorphic associations working for reviews
